// <auto-generated />
using System;
using AuctionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionService.Data.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AuctionService.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentHighBid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HighBidder")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Injury")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservePrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SoldAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("AuctionService.Entities.AuctionBidder", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bidder")
                        .HasColumnType("TEXT");

                    b.HasKey("AuctionId", "Bidder");

                    b.HasIndex("Bidder");

                    b.ToTable("AuctionBidders");
                });

            modelBuilder.Entity("AuctionService.Entities.AuctionWatcher", b =>
                {
                    b.Property<Guid>("AuctionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Watcher")
                        .HasColumnType("TEXT");

                    b.HasKey("AuctionId", "Watcher");

                    b.HasIndex("Watcher");

                    b.ToTable("AuctionWatchers");
                });

            modelBuilder.Entity("AuctionService.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("League")
                        .HasColumnType("TEXT");

                    b.Property<string>("Match")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opponent")
                        .HasColumnType("TEXT");

                    b.Property<string>("PitchPhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PitToPit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollarPhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("WashPhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelPhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoaUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.HasIndex("Club");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("AuctionService.Entities.AuctionBidder", b =>
                {
                    b.HasOne("AuctionService.Entities.Auction", "Auction")
                        .WithMany("Bidders")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionService.Entities.AuctionWatcher", b =>
                {
                    b.HasOne("AuctionService.Entities.Auction", "Auction")
                        .WithMany("Watchers")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionService.Entities.Item", b =>
                {
                    b.HasOne("AuctionService.Entities.Auction", "Auction")
                        .WithOne("Item")
                        .HasForeignKey("AuctionService.Entities.Item", "AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionService.Entities.Auction", b =>
                {
                    b.Navigation("Bidders");

                    b.Navigation("Watchers");

                    b.Navigation("Item")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
